scrape_configs:
  - job_name: 'otel-collector'
    scrape_internal: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: 'goapp'
    scrape_internal: 10s
    static_configs:
      - targets: ['goapp:8080']
